## Importing the libraries


In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [28]:
dataset = pd.read_csv('newimport85.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [29]:
dataset.shape

(205, 22)

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2,3,4,5,11,12,14])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [38]:
X

array([[1.00e+00, 0.00e+00, 1.00e+00, ..., 1.11e+02, 5.00e+03, 2.10e+01],
       [1.00e+00, 0.00e+00, 1.00e+00, ..., 1.11e+02, 5.00e+03, 2.10e+01],
       [1.00e+00, 0.00e+00, 1.00e+00, ..., 1.54e+02, 5.00e+03, 1.90e+01],
       ...,
       [1.00e+00, 0.00e+00, 1.00e+00, ..., 1.34e+02, 5.50e+03, 1.80e+01],
       [1.00e+00, 1.00e+00, 0.00e+00, ..., 1.06e+02, 4.80e+03, 2.60e+01],
       [1.00e+00, 0.00e+00, 1.00e+00, ..., 1.14e+02, 5.40e+03, 1.90e+01]])

In [36]:
import statsmodels
# import statsmodels.formula.api as sm
import statsmodels.api as sm
X=np.append(arr=np.ones((205,1)).astype(int),values=X,axis=1)
X_opt=np.array(X[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]],dtype=int)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.559
Model:                            OLS   Adj. R-squared:                  0.527
Method:                 Least Squares   F-statistic:                     17.24
Date:                Fri, 22 Jul 2022   Prob (F-statistic):           6.16e-27
Time:                        18:01:55   Log-Likelihood:                -2045.3
No. Observations:                 205   AIC:                             4121.
Df Residuals:                     190   BIC:                             4171.
Df Model:                          14                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6524.9714    539.163     12.102      0.000    5461.456    7588.487
x1          3168.6138    863.889      3.668      0.000    1464.568    4872.659
x2          3356.3577    699.893      4.796      0.000    1975.799    4736.916
x3          1436.2822    594.152      2.417      0.017     264.301    2608.264
x4          5088.6892    637.708      7.980      0.000    3830.793    6346.586
x5          3733.9683    660.845      5.650      0.000    2430.432    5037.504
x6          2791.0031    644.378      4.331      0.000    1519.949    4062.057
x7          3329.3805   1968.406      1.691      0.092    -553.356    7212.118
x8          2022.0220   1806.580      1.119      0.264   -1541.509    5585.553
x9         -1149.6287    982.639     -1.170      0.243   -3087.913     788.655
x10         2064.9596    993.416      2.079      0.039     105.419    4024.500
x11          258.2380   1343.876      0.192      0.848   -2392.595    2909.071
x12        -1752.7164   1374.458     -1.275      0.204   -4463.873     958.440
x13         -435.6314    798.140     -0.546      0.586   -2009.986    1138.723
x14         8713.3192    796.002     10.946      0.000    7143.183    1.03e+04
x15        -2723.2869   1651.841     -1.649      0.101   -5981.590     535.016
x16         9248.2583   2033.746      4.547      0.000    5236.638    1.33e+04
x17        -2512.6484   1929.599     -1.302      0.194   -6318.837    1293.540
x18        -5741.8885   5560.577     -1.033      0.303   -1.67e+04    5226.507
x19        -8515.8492   2034.719     -4.185      0.000   -1.25e+04   -4502.308
x20        -3511.2304   1180.720     -2.974      0.003   -5840.233   -1182.227
==============================================================================
Omnibus:                       70.205   Durbin-Watson:                   0.746
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              209.745
Skew:                           1.437   Prob(JB):                     2.85e-46
Kurtosis:                       7.037   Cond. No.                     7.74e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.87e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [39]:
X_opt=np.array(X[:,[0,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,18,19,20]],dtype=int)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.559
Model:                            OLS   Adj. R-squared:                  0.527
Method:                 Least Squares   F-statistic:                     17.24
Date:                Fri, 22 Jul 2022   Prob (F-statistic):           6.16e-27
Time:                        18:04:28   Log-Likelihood:                -2045.3
No. Observations:                 205   AIC:                             4121.
Df Residuals:                     190   BIC:                             4171.
Df Model:                          14                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6602.4428    705.187      9.363      0.000    5211.441    7993.444
x1          3207.3495    900.208      3.563      0.000    1431.665    4983.034
x2          3395.0934    727.376      4.668      0.000    1960.323    4829.864
x3          1475.0179    634.243      2.326      0.021     223.956    2726.079
x4          5127.4249    678.764      7.554      0.000    3788.545    6466.305
x5          3772.7040    606.782      6.218      0.000    2575.810    4969.598
x6          2829.7388    766.193      3.693      0.000    1318.402    4341.076
x7          3071.1426   2854.176      1.076      0.283   -2558.800    8701.085
x8          1763.7840   2698.818      0.654      0.514   -3559.710    7087.278
x9         -1407.8667   1657.901     -0.849      0.397   -4678.122    1862.389
x10         1806.7216   1265.469      1.428      0.155    -689.451    4302.894
x11        -1726.8926   1364.986     -1.265      0.207   -4419.366     965.581
x12         -409.8076    823.856     -0.497      0.619   -2034.887    1215.272
x13         8739.1430    828.686     10.546      0.000    7104.537    1.04e+04
x14        -2684.5512   1605.199     -1.672      0.096   -5850.851     481.748
x15         9286.9940   2095.551      4.432      0.000    5153.461    1.34e+04
x16        -2512.6484   1929.599     -1.302      0.194   -6318.837    1293.540
x17        -5741.8885   5560.577     -1.033      0.303   -1.67e+04    5226.507
x18        -8515.8492   2034.719     -4.185      0.000   -1.25e+04   -4502.308
x19        -3511.2304   1180.720     -2.974      0.003   -5840.233   -1182.227
==============================================================================
Omnibus:                       70.205   Durbin-Watson:                   0.746
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              209.745
Skew:                           1.437   Prob(JB):                     2.85e-46
Kurtosis:                       7.037   Cond. No.                     5.86e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.24e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [40]:
X_opt=np.array(X[:,[0,1,2,3,4,5,6,7,8,9,10,12,14,15,16,17,18,19,20]],dtype=int)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.559
Model:                            OLS   Adj. R-squared:                  0.527
Method:                 Least Squares   F-statistic:                     17.24
Date:                Fri, 22 Jul 2022   Prob (F-statistic):           6.16e-27
Time:                        18:07:20   Log-Likelihood:                -2045.3
No. Observations:                 205   AIC:                             4121.
Df Residuals:                     190   BIC:                             4171.
Df Model:                          14                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6465.8403    819.080      7.894      0.000    4850.182    8081.498
x1          3139.0482    926.713      3.387      0.001    1311.081    4967.016
x2          3326.7921    753.296      4.416      0.000    1840.895    4812.689
x3          1406.7166    644.892      2.181      0.030     134.649    2678.784
x4          5059.1237    730.684      6.924      0.000    3617.829    6500.419
x5          3704.4028    626.966      5.908      0.000    2467.694    4941.111
x6          2761.4375    805.574      3.428      0.001    1172.419    4350.456
x7          3071.1426   2854.176      1.076      0.283   -2558.800    8701.085
x8          1763.7840   2698.818      0.654      0.514   -3559.710    7087.278
x9         -1407.8667   1657.901     -0.849      0.397   -4678.122    1862.389
x10         1806.7216   1265.469      1.428      0.155    -689.451    4302.894
x11        -1317.0849   2018.860     -0.652      0.515   -5299.343    2665.173
x12         9148.9506    945.783      9.673      0.000    7283.368     1.1e+04
x13        -2752.8525   1594.507     -1.726      0.086   -5898.063     392.358
x14         9218.6927   2124.228      4.340      0.000    5028.593    1.34e+04
x15        -2512.6484   1929.599     -1.302      0.194   -6318.837    1293.540
x16        -5741.8885   5560.577     -1.033      0.303   -1.67e+04    5226.507
x17        -8515.8492   2034.719     -4.185      0.000   -1.25e+04   -4502.308
x18        -3511.2304   1180.720     -2.974      0.003   -5840.233   -1182.227
==============================================================================
Omnibus:                       70.205   Durbin-Watson:                   0.746
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              209.745
Skew:                           1.437   Prob(JB):                     2.85e-46
Kurtosis:                       7.037   Cond. No.                     4.04e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.36e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [41]:
X_opt=np.array(X[:,[0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,20]],dtype=int)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.558
Model:                            OLS   Adj. R-squared:                  0.528
Method:                 Least Squares   F-statistic:                     18.58
Date:                Fri, 22 Jul 2022   Prob (F-statistic):           1.71e-27
Time:                        18:08:14   Log-Likelihood:                -2045.6
No. Observations:                 205   AIC:                             4119.
Df Residuals:                     191   BIC:                             4166.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6347.1994    797.435      7.960      0.000    4774.290    7920.109
x1          3119.6045    924.840      3.373      0.001    1295.393    4943.816
x2          3227.5949    736.680      4.381      0.000    1774.522    4680.668
x3          1406.6943    643.922      2.185      0.030     136.584    2676.805
x4          4940.5051    706.636      6.992      0.000    3546.693    6334.317
x5          3643.1807    618.971      5.886      0.000    2422.285    4864.077
x6          2704.0187    799.547      3.382      0.001    1126.942    4281.095
x7          3222.0488   2840.507      1.134      0.258   -2380.743    8824.840
x8          1900.8225   2686.582      0.708      0.480   -3398.359    7200.004
x9         -1225.6081   1631.734     -0.751      0.454   -4444.141    1992.925
x10         1952.9854   1243.576      1.570      0.118    -499.921    4405.892
x11         9270.4465    925.871     10.013      0.000    7444.202    1.11e+04
x12        -2883.6155   1579.479     -1.826      0.069   -5999.077     231.846
x13         9230.8149   2120.950      4.352      0.000    5047.321    1.34e+04
x14        -2333.3493   1907.052     -1.224      0.223   -6094.938    1428.239
x15        -5639.6010   5550.003     -1.016      0.311   -1.66e+04    5307.568
x16        -8292.1332   2002.597     -4.141      0.000   -1.22e+04   -4342.087
x17        -3300.3043   1133.883     -2.911      0.004   -5536.845   -1063.764
==============================================================================
Omnibus:                       70.349   Durbin-Watson:                   0.742
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              211.772
Skew:                           1.436   Prob(JB):                     1.03e-46
Kurtosis:                       7.067   Cond. No.                     4.94e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.26e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [42]:
X_opt=np.array(X[:,[0,1,2,3,4,5,6,7,9,10,14,15,16,17,18,19,20]],dtype=int)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.557
Model:                            OLS   Adj. R-squared:                  0.530
Method:                 Least Squares   F-statistic:                     20.14
Date:                Fri, 22 Jul 2022   Prob (F-statistic):           4.70e-28
Time:                        18:09:15   Log-Likelihood:                -2045.8
No. Observations:                 205   AIC:                             4118.
Df Residuals:                     192   BIC:                             4161.
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6636.9422    683.360      9.712      0.000    5289.086    7984.799
x1          3289.3236    892.027      3.687      0.000    1529.892    5048.755
x2          3347.6186    715.949      4.676      0.000    1935.483    4759.754
x3          1560.1603    605.501      2.577      0.011     365.873    2754.447
x4          5076.7820    678.994      7.477      0.000    3737.537    6416.027
x5          3613.6554    616.759      5.859      0.000    2397.163    4830.148
x6          3023.2869    659.180      4.586      0.000    1723.122    4323.452
x7          2387.9222   2580.933      0.925      0.356   -2702.701    7478.545
x8         -1841.3252   1378.506     -1.336      0.183   -4560.286     877.636
x9          1569.6417   1117.884      1.404      0.162    -635.269    3774.552
x10         9368.8876    914.166     10.249      0.000    7565.791    1.12e+04
x11        -3158.1881   1529.069     -2.065      0.040   -6174.119    -142.257
x12         9795.1303   1962.710      4.991      0.000    5923.887    1.37e+04
x13        -2371.1294   1903.824     -1.245      0.214   -6126.225    1383.966
x14        -5730.2530   5541.303     -1.034      0.302   -1.67e+04    5199.393
x15        -8407.7565   1993.320     -4.218      0.000   -1.23e+04   -4476.138
x16        -3249.4751   1130.132     -2.875      0.004   -5478.543   -1020.407
==============================================================================
Omnibus:                       73.995   Durbin-Watson:                   0.741
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              235.164
Skew:                           1.493   Prob(JB):                     8.61e-52
Kurtosis:                       7.314   Cond. No.                     6.15e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.74e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [43]:
X_opt=np.array(X[:,[0,1,2,3,4,5,6,9,10,14,15,16,17,18,19,20]],dtype=int)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.555
Model:                            OLS   Adj. R-squared:                  0.530
Method:                 Least Squares   F-statistic:                     21.91
Date:                Fri, 22 Jul 2022   Prob (F-statistic):           1.47e-28
Time:                        18:09:53   Log-Likelihood:                -2046.3
No. Observations:                 205   AIC:                             4117.
Df Residuals:                     193   BIC:                             4156.
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6797.5537    660.697     10.288      0.000    5494.441    8100.667
x1          3366.2255    887.815      3.792      0.000    1615.160    5117.291
x2          3431.3281    709.945      4.833      0.000    2031.082    4831.574
x3          1662.5575    595.078      2.794      0.006     488.866    2836.249
x4          5134.9962    675.820      7.598      0.000    3802.055    6467.938
x5          3564.5851    614.245      5.803      0.000    2353.091    4776.079
x6          3232.9686    618.767      5.225      0.000    2012.556    4453.381
x7         -2307.2910   1282.735     -1.799      0.074   -4837.270     222.688
x8          1287.6666   1075.137      1.198      0.233    -832.860    3408.193
x9          9387.1068    913.613     10.275      0.000    7585.160    1.12e+04
x10        -3218.9317   1527.089     -2.108      0.036   -6230.858    -207.005
x11         1.002e+04   1947.347      5.144      0.000    6175.670    1.39e+04
x12        -2095.9926   1879.754     -1.115      0.266   -5803.491    1611.506
x13        -5778.1626   5538.994     -1.043      0.298   -1.67e+04    5146.570
x14        -8454.6805   1991.932     -4.244      0.000   -1.24e+04   -4525.930
x15        -3254.4091   1129.698     -2.881      0.004   -5482.548   -1026.270
==============================================================================
Omnibus:                       70.745   Durbin-Watson:                   0.731
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              213.983
Skew:                           1.443   Prob(JB):                     3.42e-47
Kurtosis:                       7.089   Cond. No.                     4.39e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.4e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [44]:
X_opt=np.array(X[:,[0,1,2,3,4,5,6,9,10,14,15,16,18,19,20]],dtype=int)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.552
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     23.95
Date:                Fri, 22 Jul 2022   Prob (F-statistic):           5.29e-29
Time:                        18:10:34   Log-Likelihood:                -2047.0
No. Observations:                 205   AIC:                             4116.
Df Residuals:                     194   BIC:                             4152.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6741.6397    659.204     10.227      0.000    5441.513    8041.766
x1          3360.1608    888.355      3.782      0.000    1608.087    5112.234
x2          3381.4790    708.980      4.770      0.000    1983.181    4779.777
x3          1652.6154    595.384      2.776      0.006     478.358    2826.872
x4          5089.0244    674.984      7.539      0.000    3757.775    6420.274
x5          3558.9991    614.609      5.791      0.000    2346.825    4771.173
x6          3182.6407    617.505      5.154      0.000    1964.756    4400.526
x7         -2285.9373   1283.396     -1.781      0.076   -4817.138     245.263
x8          1267.6439   1075.661      1.178      0.240    -853.847    3389.135
x9          9233.8859    903.786     10.217      0.000    7451.379     1.1e+04
x10        -3594.0996   1490.496     -2.411      0.017   -6533.756    -654.443
x11         1.034e+04   1927.391      5.363      0.000    6534.408    1.41e+04
x12        -5105.0944   5509.456     -0.927      0.355    -1.6e+04    5761.026
x13        -7804.3686   1905.832     -4.095      0.000   -1.16e+04   -4045.558
x14        -2696.4782   1013.476     -2.661      0.008   -4695.323    -697.633
==============================================================================
Omnibus:                       73.973   Durbin-Watson:                   0.721
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              243.195
Skew:                           1.477   Prob(JB):                     1.55e-53
Kurtosis:                       7.444   Cond. No.                     7.20e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is  2e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [45]:
X_opt=np.array(X[:,[0,1,2,3,4,5,6,9,10,14,15,16,19,20]],dtype=int)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.551
Model:                            OLS   Adj. R-squared:                  0.530
Method:                 Least Squares   F-statistic:                     26.54
Date:                Fri, 22 Jul 2022   Prob (F-statistic):           1.50e-29
Time:                        18:11:15   Log-Likelihood:                -2047.4
No. Observations:                 205   AIC:                             4115.
Df Residuals:                     195   BIC:                             4148.
Df Model:                           9                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6746.5306    658.944     10.238      0.000    5446.959    8046.102
x1          3346.8889    887.917      3.769      0.000    1595.735    5098.043
x2          3399.6417    708.452      4.799      0.000    2002.430    4796.853
x3          1634.7569    594.856      2.748      0.007     461.579    2807.935
x4          5111.7737    674.293      7.581      0.000    3781.930    6441.617
x5          3560.8352    614.383      5.796      0.000    2349.146    4772.524
x6          3185.6954    617.272      5.161      0.000    1968.309    4403.082
x7         -2381.6226   1278.771     -1.862      0.064   -4903.620     140.375
x8          1249.7643   1075.098      1.162      0.246    -870.548    3370.076
x9          9168.7348    900.720     10.179      0.000    7392.332    1.09e+04
x10        -3646.1100   1488.898     -2.449      0.015   -6582.521    -709.699
x11         1.039e+04   1925.714      5.397      0.000    6594.739    1.42e+04
x12        -7688.5716   1901.041     -4.044      0.000   -1.14e+04   -3939.331
x13        -2596.5931   1007.361     -2.578      0.011   -4583.315    -609.871
==============================================================================
Omnibus:                       74.956   Durbin-Watson:                   0.733
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              247.252
Skew:                           1.497   Prob(JB):                     2.04e-54
Kurtosis:                       7.470   Cond. No.                     5.15e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.91e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [46]:
X_opt=np.array(X[:,[0,1,2,3,4,5,6,9,14,15,16,19,20]],dtype=int)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.547
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     29.63
Date:                Fri, 22 Jul 2022   Prob (F-statistic):           5.12e-30
Time:                        18:11:54   Log-Likelihood:                -2048.1
No. Observations:                 205   AIC:                             4114.
Df Residuals:                     196   BIC:                             4144.
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6913.6199    643.652     10.741      0.000    5644.247    8182.992
x1          3474.2846    881.918      3.939      0.000    1735.018    5213.551
x2          3439.3353    708.262      4.856      0.000    2042.542    4836.128
x3          1716.2525    591.240      2.903      0.004     550.244    2882.261
x4          5197.3673    670.861      7.747      0.000    3874.334    6520.401
x5          3722.6088    598.951      6.215      0.000    2541.393    4903.824
x6          3191.0111    617.808      5.165      0.000    1972.606    4409.416
x7         -3188.9935   1074.684     -2.967      0.003   -5308.422   -1069.565
x8          9140.1506    901.191     10.142      0.000    7362.875    1.09e+04
x9         -3214.0108   1443.044     -2.227      0.027   -6059.898    -368.124
x10         1.013e+04   1913.886      5.292      0.000    6353.178    1.39e+04
x11        -7773.7640   1901.329     -4.089      0.000   -1.15e+04   -4024.074
x12        -2509.0428   1005.442     -2.495      0.013   -4491.916    -526.170
==============================================================================
Omnibus:                       74.700   Durbin-Watson:                   0.704
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              241.035
Skew:                           1.502   Prob(JB):                     4.57e-53
Kurtosis:                       7.381   Cond. No.                     4.96e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.04e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

 These columns are statistically significant over here according the backward elimination 0,1,2,3,4,5,6,9,14,15,16,19,20  

In [47]:
dataset.drop(["length","width","curb-weight","engine-type","num-of-cylinders","engine-size","compression-ratio","horsepower"],axis=1,inplace=True)

In [48]:
dataset.to_csv("IMPORT85.CSV",index=False)

## Now making machine learning model with the new dataset after performing backward elimination

In [146]:
dataset = pd.read_csv('IMPORT85.CSV')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [87]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2,3,4,5,8])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

In [131]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()
X[:,0:6]=encoder.fit_transform(X[:,0:6])

In [140]:
X[:,0:6]

array([[1.0, 0.0, 1.0, 0.0, 2.0, 0.0],
       [1.0, 0.0, 1.0, 0.0, 2.0, 0.0],
       [1.0, 0.0, 1.0, 2.0, 2.0, 0.0],
       ...,
       [1.0, 0.0, 0.0, 3.0, 2.0, 0.0],
       [0.0, 1.0, 0.0, 3.0, 2.0, 0.0],
       [1.0, 1.0, 0.0, 3.0, 2.0, 0.0]], dtype=object)

In [134]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()
X[:,8:9]=encoder.fit_transform(X[:,8:9])

In [141]:
X[:,8:9]

array([[5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [5.0],
       [1.0],
       [1.0],
       [1.0],
       [5.0],
       [1.0],
       [4.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [5.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [7.0],
       [5.0],
       [5.0],
       [5.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [2.0],
       [2.0],
       [2.0],
       [5.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [3.0],
       [1.0],
       [5.0],
       [3.0],
       [3.0],
       [3.0],
       [3.0],
       [3.0],
      

In [135]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

## Training the model on the training set

In [136]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=5,random_state=0)
regressor.fit(X_train,y_train)

RandomForestRegressor(n_estimators=5, random_state=0)

## Predicting the new results

In [137]:
y_pred=regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[ 6127.18  6669.  ]
 [ 7349.    7999.  ]
 [ 6301.6   6338.  ]
 [ 8424.8  13207.13]
 [ 8569.8  10295.  ]
 [28204.8  25552.  ]
 [ 7264.    8249.  ]
 [ 6058.85  5151.  ]
 [ 6346.    6488.  ]
 [ 9665.   10245.  ]
 [14617.6  17450.  ]
 [10126.6  17669.  ]
 [15781.   16515.  ]
 [ 8275.    9095.  ]
 [14700.   12964.  ]
 [ 9592.6  11199.  ]
 [10033.6   9980.  ]
 [ 5701.08  6529.  ]
 [15912.   18150.  ]
 [12116.2  11259.  ]
 [10800.    8948.  ]
 [ 6295.88  6855.  ]
 [15438.   16925.  ]
 [ 7903.4   7957.  ]
 [11119.4   9989.  ]
 [ 5701.08  7129.  ]
 [14869.   14489.  ]
 [ 8635.8   7995.  ]
 [ 6689.3   6229.  ]
 [ 7224.93  7295.  ]
 [ 8600.2   8058.  ]
 [10712.6   8921.  ]
 [25504.4  41315.  ]
 [ 9589.2   9295.  ]
 [16341.93 17950.  ]
 [ 7507.2   7775.  ]
 [ 7669.    8558.  ]
 [39614.   32250.  ]
 [20819.   15645.  ]
 [17943.   22625.  ]
 [ 6241.37  5118.  ]]


## Evaluating the performance of the machine learning model

In [138]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7837292454874365

In [139]:
print(X)

[[1.0 0.0 1.0 ... 2.68 5000.0 21]
 [1.0 0.0 1.0 ... 2.68 5000.0 21]
 [1.0 0.0 1.0 ... 3.47 5000.0 19]
 ...
 [1.0 0.0 0.0 ... 2.87 5500.0 18]
 [0.0 1.0 0.0 ... 3.4 4800.0 26]
 [1.0 1.0 0.0 ... 3.15 5400.0 19]]


## Predicting the new results
### What will be the price of the car having following features?
Car is of diesel,turbo with four doors having sedan body style with rwd drive wheel with engine at the front location with fuel system mpfi

In [143]:
print(regressor.predict([[0,1,0,3,2,0,104,51.5,5,3.5,3.7,5600,24]]))

[17791.8]
