## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset


In [3]:
dataset=pd.read_csv("newimport85.csv")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [5]:
dataset.isnull().sum() # no missing values present in the dataset over here

fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
price                0
dtype: int64

## Encoding the independent variables

In [6]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()
X[:,0:6]=encoder.fit_transform(X[:,0:6])

## Encoded variables
1 for gas and 0 for diesal in fuel-type column

In [7]:
print(X[:,0:1])

[[1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]

## Encoded variables
1 for turbo and 0 for std for aspiration column

In [8]:
print(X[:,1:2])

[[0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]

## Encoded variables
0 for four and 1 for two in num_of_doors column

In [9]:
print(X[:,2:3])

[[1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]

## Encoded variables
3 for sedan ,4 for wagon, 2 for hatchback, 0 for convertible and 1 for hardtop

In [10]:
print(X[:,3:4])

[[0.0]
 [0.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [4.0]
 [3.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [2.0]
 [2.0]
 [3.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [4.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [4.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [2.0]
 [3.0]
 [3.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [4.0]
 [1.0]
 [3.0]
 [3.0]
 [0.0]
 [3.0]
 [1.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [4.0]
 [3.0]
 [2.0]
 [3.0]
 [4.0]
 [1.0]
 [2.0]
 [3.0]
 [3.0]
 [4.0]
 [3.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]
 [4.0]
 [4.0]
 [3.0]
 [3.0]
 [4.0]
 [4.0]
 [3.0]
 [3.0]
 [3.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]
 [4.0]
 [2.0]
 [2.0]
 [1.0]
 [1.0]
 [0.0]
 [2.0]
 [4.0]
 [2.0]
 [2.0]
 [3.0]
 [2.0]
 [3.0]
 [2.0]
 [3.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]

## Encoded variables
2 for rwd,1 for fwd and 0 for 4wd in drive-wheels columns

In [11]:
print(X[:,4:5])

[[2.0]
 [2.0]
 [2.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [2.0]
 [1.0]
 [1.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [1.0]
 [1.0]

## Encoded variables
0 for front and 1 for rear for the engine location column

In [12]:
print(X[:,5:6])

[[0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]

In [14]:
X[:,11:13]=encoder.fit_transform(X[:,11:13])
X[:,14:15]=encoder.fit_transform(X[:,14:15])

## Encoded variables
0 for dohc , 5 for ohcv, 3 for ohc, 2 for I , 4 for ohcf and 1 for dohcv

In [15]:
print(X[:,11:12])

[[0.0]
 [0.0]
 [5.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [0.0]
 [0.0]
 [5.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [6.0]
 [6.0]
 [6.0]
 [6.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [4.0]
 [4.0]
 [4.0]
 [1.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [0.0]
 [0.0]
 [4.0]
 [4.0]
 [4.0]
 [4.0]
 [4.0]

## Encoded variables
2 for four,3 for six,1 for five,5 for twelve,6 for two, 0 for eight for number of cyclinder column

In [16]:
print(X[:,12:13])

[[2.0]
 [2.0]
 [3.0]
 [2.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [4.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]
 [5.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [6.0]
 [6.0]
 [6.0]
 [6.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [3.0]
 [3.0]
 [3.0]
 [0.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]
 [2.0]

## Encoded variables
5 for mpfi,3 for idi,1 for 2bbl,4 for mfi,0 for 1bbl,7 for spfi,2 for 4bbl,6 for spdi

In [17]:
print(X[:,14:15])

[[5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [5.0]
 [1.0]
 [1.0]
 [1.0]
 [5.0]
 [1.0]
 [4.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [5.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [7.0]
 [5.0]
 [5.0]
 [5.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [2.0]
 [2.0]
 [2.0]
 [5.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [3.0]
 [1.0]
 [5.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [3.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [1.0]
 [1.0]
 [1.0]
 [6.0]
 [6.0]
 [1.0]
 [6.0]
 [6.0]
 [6.0]
 [1.0]
 [1.0]
 [6.0]
 [6.0]
 [1.0]
 [3.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [3.0]
 [5.0]
 [3.0]
 [5.0]
 [3.0]
 [5.0]
 [3.0]
 [5.0]
 [3.0]
 [5.0]
 [1.0]
 [6.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [6.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [5.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]

In [18]:
dataset.shape 

(205, 22)

## Splitting the dataset into training set and testing set

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [20]:
from sklearn.feature_selection import VarianceThreshold
var_thres=VarianceThreshold(threshold=0)
var_thres.fit(X_train)

VarianceThreshold(threshold=0)

In [22]:
var_thres.get_support() # as we are getting true for each and every feature then it means all of them have high variance and they can become a good predictor

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [26]:
from sklearn.feature_selection import mutual_info_regression
# determine the mutual information
mutual_info = mutual_info_regression(X_train, y_train)
mutual_info

array([0.04257731, 0.09262726, 0.        , 0.06705468, 0.29130673,
       0.00141193, 0.50368028, 0.57039475, 0.67588376, 0.36641719,
       0.90105669, 0.14751835, 0.31782189, 0.83795896, 0.46888485,
       0.47426874, 0.44423304, 0.16956726, 0.90684946, 0.15101075,
       0.75774423])

In [28]:
mutual_info = pd.Series(mutual_info)
mutual_info.sort_values(ascending=False)

18    0.906849
10    0.901057
13    0.837959
20    0.757744
8     0.675884
7     0.570395
6     0.503680
15    0.474269
14    0.468885
16    0.444233
9     0.366417
12    0.317822
4     0.291307
17    0.169567
19    0.151011
11    0.147518
1     0.092627
3     0.067055
0     0.042577
5     0.001412
2     0.000000
dtype: float64

In [30]:
from sklearn.feature_selection import SelectKBest
#No we Will select the  top 5 important features
sel_five_cols = SelectKBest(mutual_info_regression, k=10)
sel_five_cols.fit(X_train, y_train)
# X_train.columns[sel_five_cols.get_support()]

SelectKBest(score_func=<function mutual_info_regression at 0x000002A31E982E60>)

In [32]:
sel_five_cols.get_support() # over here i am selecting the best 10 predictors for my machine learning model

array([False, False, False, False, False, False,  True,  True,  True,
       False,  True, False, False,  True,  True,  True,  True, False,
        True, False,  True])

In [33]:
dataset.drop(["fuel-type","aspiration","num-of-doors","body-style","drive-wheels","engine-location","height",
             "engine-type","num-of-cylinders","compression-ratio","peak-rpm"],axis=1,inplace=True)

In [34]:
dataset

wheel-base  length  width  curb-weight  engine-size fuel-system  bore  \
0          88.6   168.8   64.1         2548          130        mpfi  3.47   
1          88.6   168.8   64.1         2548          130        mpfi  3.47   
2          94.5   171.2   65.5         2823          152        mpfi  2.68   
3          99.8   176.6   66.2         2337          109        mpfi  3.19   
4          99.4   176.6   66.4         2824          136        mpfi  3.19   
..          ...     ...    ...          ...          ...         ...   ...   
200       109.1   188.8   68.9         2952          141        mpfi  3.78   
201       109.1   188.8   68.8         3049          141        mpfi  3.78   
202       109.1   188.8   68.9         3012          173        mpfi  3.58   
203       109.1   188.8   68.9         3217          145         idi  3.01   
204       109.1   188.8   68.9         3062          141        mpfi  3.78   

     stroke  horsepower  city-mpg    price  
0      2.68       111.0        21  13495.0  
1      2.68       111.0        21  16500.0  
2      3.47       154.0        19  16500.0  
3      3.40       102.0        24  13950.0  
4      3.40       115.0        18  17450.0  
..      ...         ...       ...      ...  
200    3.15       114.0        23  16845.0  
201    3.15       160.0        19  19045.0  
202    2.87       134.0        18  21485.0  
203    3.40       106.0        26  22470.0  
204    3.15       114.0        19  22625.0  

[205 rows x 11 columns]

In [35]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [36]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()
X[:,5:6]=encoder.fit_transform(X[:,5:6])

## Encoded variables
5 for mpfi,3 for idi,1 for 2bbl,4 for mfi,0 for 1bbl,7 for spfi,2 for 4bbl,6 for spdi

In [38]:
X[:,5:6]

array([[5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [5.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [5.0],
       [1.0],
       [1.0],
       [1.0],
       [5.0],
       [1.0],
       [4.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [0.0],
       [5.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [7.0],
       [5.0],
       [5.0],
       [5.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [2.0],
       [2.0],
       [2.0],
       [5.0],
       [1.0],
       [1.0],
       [1.0],
       [1.0],
       [3.0],
       [1.0],
       [5.0],
       [3.0],
       [3.0],
       [3.0],
       [3.0],
       [3.0],
      

In [65]:
y=y.reshape(len(y),1)

## Feature Scaling

In [67]:
from sklearn.preprocessing import MinMaxScaler
sc1=MinMaxScaler(feature_range=(0,1))


X_train=sc1.fit_transform(X_train)
X_test=sc1.transform(X_test)




## Training the model on the training set

In [76]:
from sklearn.tree import DecisionTreeRegressor


regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

## Predicting the new results

In [77]:
y_pred=regressor.predict(sc1.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[ 6095.    6795.  ]
 [15690.   15750.  ]
 [11248.   15250.  ]
 [ 5399.    5151.  ]
 [10198.    9995.  ]
 [17669.   11199.  ]
 [ 5572.    5389.  ]
 [ 6918.    7898.  ]
 [18399.   17199.  ]
 [ 7129.    6529.  ]
 [21105.   20970.  ]
 [35056.   13207.13]
 [11845.   10945.  ]
 [13200.   18344.  ]
 [ 6575.   13207.13]
 [17669.    9989.  ]
 [11850.    9295.  ]
 [17710.   18920.  ]
 [ 9095.    7895.  ]
 [ 6338.    6488.  ]
 [ 9279.    9959.  ]
 [15040.   15580.  ]
 [11248.    9895.  ]
 [17669.   11549.  ]
 [16558.   15998.  ]
 [ 7499.    5118.  ]
 [ 7738.    6938.  ]
 [15040.   16695.  ]
 [ 9258.    8358.  ]
 [ 6649.    5499.  ]
 [ 8195.    7975.  ]
 [13845.   12290.  ]
 [16503.   22018.  ]
 [ 9370.    8948.  ]
 [ 7299.    6849.  ]
 [30760.   41315.  ]
 [ 9980.   11595.  ]
 [16503.   18150.  ]
 [ 5572.    6377.  ]
 [40960.   45400.  ]
 [ 6575.   13207.13]]


## Evaluatinng the performance of the machine learning model

In [78]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6631599896575919

## Using K fold cross validation

In [79]:
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=regressor,X=X_train,y=y_train,cv=10)
print("Accuracy:{:.2f}%".format(accuracies.mean()*100))
print("Standard deviation:{:.2f}%".format(accuracies.std()*100))

Accuracy:88.01%
Standard deviation:6.10%
