## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dataset=pd.read_csv("machine.csv")
X=dataset.iloc[:,2:-1].values # we are not considering the vendor name over here
y=dataset.iloc[:,-1].values # this one is dependent variable that we want to predict

In [3]:
print(X)

[[  125   256  6000 ...    16   128   198]
 [   29  8000 32000 ...     8    32   269]
 [   29  8000 32000 ...     8    32   220]
 ...
 [  125  2000  8000 ...     2    14    52]
 [  480   512  8000 ...     0     0    67]
 [  480  1000  4000 ...     0     0    45]]


In [4]:
print(y)

[ 199  253  253  253  132  290  381  381  749 1238   23   24   70  117
   15   64   23   29   22  124   35   39   40   45   28   21   28   22
   28   27  102  102   74   74  138  136   23   29   44   30   41   74
   74   74   54   41   18   28   36   38   34   19   72   36   30   56
   42   34   34   34   34   34   19   75  113  157   18   20   28   33
   47   54   20   23   25   52   27   50   18   53   23   30   73   20
   25   28   29   32  175   57  181  181   32   82  171  361  350  220
  113   15   21   35   18   20   20   28   45   18   17   26   28   28
   31   31   42   76   76   26   59   65  101  116   18   20   20   30
   44   44   82   82  128   37   46   46   80   88   88   33   46   29
   53   53   41   86   95  107  117  119  120   48  126  266  270  426
  151  267  603   19   21   26   35   41   47   62   78   80   80  142
  281  190   21   25   67   24   24   64   25   20   29   43   53   19
   22   31   41   47   99   67   81  149  183  275  382   56  182  227
  341 

## Spliiting the dataset into training set and testing set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the linear regression model on the training set

In [10]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=10,random_state=0)
regressor.fit(X_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

## Predicting the test set results

In [11]:
y_pred=regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[ 68.7  70. ]
 [ 23.1  23. ]
 [ 72.4  74. ]
 [274.  290. ]
 [ 64.6  67. ]
 [ 20.5  20. ]
 [ 81.2  76. ]
 [ 17.8  18. ]
 [184.7 181. ]
 [188.4 151. ]
 [ 42.6  41. ]
 [410.7 603. ]
 [ 91.4  72. ]
 [133.6 149. ]
 [314.9 350. ]
 [ 30.2  29. ]
 [ 56.5  50. ]
 [ 29.5  29. ]
 [ 18.   18. ]
 [ 20.6  22. ]
 [ 20.5  21. ]
 [ 65.4  64. ]
 [408.5 381. ]
 [ 57.4  56. ]
 [ 31.4  32. ]
 [ 74.8  80. ]
 [ 29.1  30. ]
 [ 19.8  20. ]
 [ 20.7  21. ]
 [ 34.   41. ]
 [ 52.6  52. ]
 [ 69.   48. ]
 [ 43.1  46. ]
 [ 45.4  54. ]
 [109.7  99. ]
 [ 82.5 107. ]
 [ 27.9  25. ]
 [ 64.4  59. ]
 [ 21.9  23. ]
 [ 77.4  88. ]
 [260.4 183. ]
 [ 39.8  40. ]]


## Predicting the New results

In [17]:
print(regressor.predict([[10,8000,3200,32,8,32,220]]))
# the more data we have the more confidence we have in saying that our prediction is accurate

[112.1]


## Evaluating the model performance

In [13]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9130884559266086