## Importing the essential libraries over here

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Importing the dataset over here

In [2]:
data=pd.read_csv("liver_cirrhosis.csv")

In [3]:
data.head()

N_Days Status     Drug    Age Sex Ascites Hepatomegaly Spiders Edema  \
0    2221      C  Placebo  18499   F       N            Y       N     N   
1    1230      C  Placebo  19724   M       Y            N       Y     N   
2    4184      C  Placebo  11839   F       N            N       N     N   
3    2090      D  Placebo  16467   F       N            N       N     N   
4    2105      D  Placebo  21699   F       N            Y       N     N   

   Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  Tryglicerides  \
0        0.5        149.0     4.04   227.0     598.0   52.70           57.0   
1        0.5        219.0     3.93    22.0     663.0   45.00           75.0   
2        0.5        320.0     3.54    51.0    1243.0  122.45           80.0   
3        0.7        255.0     3.74    23.0    1024.0   77.50           58.0   
4        1.9        486.0     3.54    74.0    1052.0  108.50          109.0   

   Platelets  Prothrombin  Stage  
0      256.0          9.9      1  
1      220.0         10.8      2  
2      225.0         10.0      2  
3      151.0         10.2      2  
4      151.0         11.5      1

In [5]:
data.shape

(25000, 19)

## Taking care of duplicate observations if present over here

In [4]:
data.duplicated().sum()

15361

In [6]:
data.drop_duplicates(inplace=True)

## Taking care of missing values if present over here

In [7]:
data.isnull().sum()

N_Days           0
Status           0
Drug             0
Age              0
Sex              0
Ascites          0
Hepatomegaly     0
Spiders          0
Edema            0
Bilirubin        0
Cholesterol      0
Albumin          0
Copper           0
Alk_Phos         0
SGOT             0
Tryglicerides    0
Platelets        0
Prothrombin      0
Stage            0
dtype: int64

## Filtering all the numerical features over here

In [9]:
numerical_features=[feature for feature in data.columns if data[feature].dtype!='O']
for feature in numerical_features:
  print(feature)

N_Days
Age
Bilirubin
Cholesterol
Albumin
Copper
Alk_Phos
SGOT
Tryglicerides
Platelets
Prothrombin
Stage


In [10]:
data[numerical_features]

N_Days    Age  Bilirubin  Cholesterol  Albumin      Copper  \
0        2221  18499        0.5   149.000000     4.04  227.000000   
1        1230  19724        0.5   219.000000     3.93   22.000000   
2        4184  11839        0.5   320.000000     3.54   51.000000   
3        2090  16467        0.7   255.000000     3.74   23.000000   
4        2105  21699        1.9   486.000000     3.54   74.000000   
...       ...    ...        ...          ...      ...         ...   
24963    3577  17897        0.7   369.510563     3.49   97.648387   
24971    4795  23376        1.8   369.510563     3.24   97.648387   
24972    3358  24585        2.1   262.000000     3.48   58.000000   
24991    4365  21324        0.9   346.000000     3.40   81.000000   
24992     694  28650        0.8   300.000000     2.94  231.000000   

          Alk_Phos        SGOT  Tryglicerides  Platelets  Prothrombin  Stage  
0       598.000000   52.700000      57.000000      256.0          9.9      1  
1       663.000000   45.000000      75.000000      220.0         10.8      2  
2      1243.000000  122.450000      80.000000      225.0         10.0      2  
3      1024.000000   77.500000      58.000000      151.0         10.2      2  
4      1052.000000  108.500000     109.000000      151.0         11.5      1  
...            ...         ...            ...        ...          ...    ...  
24963  1982.655769  122.556346     124.702128      243.0          9.7      1  
24971  1982.655769  122.556346     124.702128      139.0         10.5      1  
24972  2045.000000   89.900000      84.000000      412.0         11.8      3  
24991  1098.000000  122.450000      90.000000      228.0         10.3      2  
24992  1794.000000  130.200000      99.000000       97.0         11.2      3  

[9639 rows x 12 columns]

## Filtering all the categorical features over here

In [12]:
cat_features=[feature for feature in data.columns if data[feature].dtype=='O']
for feature in cat_features:
  print(feature)

Status
Drug
Sex
Ascites
Hepatomegaly
Spiders
Edema


In [13]:
data[cat_features]

Status             Drug Sex Ascites Hepatomegaly Spiders Edema
0          C          Placebo   F       N            Y       N     N
1          C          Placebo   M       Y            N       Y     N
2          C          Placebo   F       N            N       N     N
3          D          Placebo   F       N            N       N     N
4          D          Placebo   F       N            Y       N     N
...      ...              ...  ..     ...          ...     ...   ...
24963      C          Placebo   F       Y            N       Y     N
24971      C          Placebo   F       Y            N       Y     N
24972      D  D-penicillamine   F       N            Y       N     N
24991      C  D-penicillamine   F       N            N       N     N
24992      D  D-penicillamine   M       Y            Y       Y     N

[9639 rows x 7 columns]

## Encoding the categorical features over here

In [14]:
for feature in cat_features:
  feature_mapping={category:index for index,category in enumerate(data[feature].unique())}
  data[feature]=data[feature].map(feature_mapping)

In [16]:
data

N_Days  Status  Drug    Age  Sex  Ascites  Hepatomegaly  Spiders  \
0        2221       0     0  18499    0        0             0        0   
1        1230       0     0  19724    1        1             1        1   
2        4184       0     0  11839    0        0             1        0   
3        2090       1     0  16467    0        0             1        0   
4        2105       1     0  21699    0        0             0        0   
...       ...     ...   ...    ...  ...      ...           ...      ...   
24963    3577       0     0  17897    0        1             1        1   
24971    4795       0     0  23376    0        1             1        1   
24972    3358       1     1  24585    0        0             0        0   
24991    4365       0     1  21324    0        0             1        0   
24992     694       1     1  28650    1        1             0        1   

       Edema  Bilirubin  Cholesterol  Albumin      Copper     Alk_Phos  \
0          0        0.5   149.000000     4.04  227.000000   598.000000   
1          0        0.5   219.000000     3.93   22.000000   663.000000   
2          0        0.5   320.000000     3.54   51.000000  1243.000000   
3          0        0.7   255.000000     3.74   23.000000  1024.000000   
4          0        1.9   486.000000     3.54   74.000000  1052.000000   
...      ...        ...          ...      ...         ...          ...   
24963      0        0.7   369.510563     3.49   97.648387  1982.655769   
24971      0        1.8   369.510563     3.24   97.648387  1982.655769   
24972      0        2.1   262.000000     3.48   58.000000  2045.000000   
24991      0        0.9   346.000000     3.40   81.000000  1098.000000   
24992      0        0.8   300.000000     2.94  231.000000  1794.000000   

             SGOT  Tryglicerides  Platelets  Prothrombin  Stage  
0       52.700000      57.000000      256.0          9.9      1  
1       45.000000      75.000000      220.0         10.8      2  
2      122.450000      80.000000      225.0         10.0      2  
3       77.500000      58.000000      151.0         10.2      2  
4      108.500000     109.000000      151.0         11.5      1  
...           ...            ...        ...          ...    ...  
24963  122.556346     124.702128      243.0          9.7      1  
24971  122.556346     124.702128      139.0         10.5      1  
24972   89.900000      84.000000      412.0         11.8      3  
24991  122.450000      90.000000      228.0         10.3      2  
24992  130.200000      99.000000       97.0         11.2      3  

[9639 rows x 19 columns]

## Creating the features and labels over here

In [17]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

## Splitting the dataset into training set and testing set to avoid the problem of overfitting over here

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Training the model on the training dataset over here

In [21]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Evaluating the performance of the model on the training dataset over here

In [22]:
y_pred=classifier.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [3 3]
 [2 2]
 ...
 [3 3]
 [3 3]
 [2 2]]


## Checking the performance of the model on testing dataset over here

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[496  81  22]
 [ 95 539  44]
 [ 24  43 584]]


0.8397302904564315